sudo: required
services:
  - docker

before_install:
  - docker build -t samir2521/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true samir2521/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-041049633754"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_VALUE