sudo: required
services:
  - docker

before_install:
  - docker build -t samir2521/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true samir2521/docker-react npm run test -- --coverage