version: "3"
services:
  frontend:
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    #user: ${CURRENT_UID}
    volumes: 
      - /app/node_modules
      - /c/Users/samir/SamirWork/DockerUdemy/frontend:/app